spring:
  application:
    name: gatewayf
  profiles:
    active: local
  cloud:
    gateway:
      default-filters:
        - name: TraceIdInserter
      routes:
        - id: apiserver
          uri: http://localhost:12001
          predicates:
            - Path=/**
          filters:
#            - AddRequestHeader=x-trace-id, ${spring.application.name}



server:
  port: 12000


logging:
  config: classpath:log4j2/log4j2-${spring.profiles.active}.xml
  file:
    name: gateway.log
    path: logs/${logging.file.name}
    pattern: .%d{yyyy-MM-dd HH:mm:ss}
  audit:
    file:
      name: gateway-audit.log
      path: logs/${logging.audit.file.name}
      pattern: .%d{yyyy-MM-dd HH:mm:ss}